import {
  X,
  Star,
  Gift,
  Share2,
  Info,
  Lock,
  Check,
  ArrowRight,
  Play,
  Activity,
  Zap,
  ShieldCheck,
  TrendingDown,
} from "lucide-react";
import {
  FaLinkedinIn,
  FaFacebookF,
  FaInstagram,
  FaYoutube,
} from "react-icons/fa";
export const iconMap = {
  x: X,
  activity: Activity,
  zap: Zap,
  "shield-check": ShieldCheck,
  "trending-down": TrendingDown,
  shield: ShieldCheck,
  rocket: Zap,
  dollar: Star,
  star: Star,
  gift: Gift,
  share: Share2,
  info: Info,
  linkedin: FaLinkedinIn,
  facebook: FaFacebookF,
  instagram: FaInstagram,
  youtube: FaYoutube,
  lock: Lock,
  check: Check,
  "arrow-right": ArrowRight,
  play: Play,
};
export type IconName = keyof typeof iconMap;
